[project]
name = "pyginvaders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.1.0",
    "flake8>=7.3.0",
    "pygame>=2.6.1",
    "pyrefly>=0.50.1",
    "pytest>=9.0.2",
]
